version: "3.8"

services:
  kirithraweb:
    build: .
    container_name: kirithraweb
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-ssl.conf:/etc/nginx/conf.d/nginx-ssl.conf
      - ./letsencrypt:/etc/letsencrypt
      - ./certbot:/var/www/certbot
    environment:
      - DOMAIN=kirithraweb.rockmypost.com
      - EMAIL=admin@kirithraweb.rockmypost.com
